export const PAGE_IS_LOADING = 'PAGE_IS_LOADING';
export const PAGE_FETCH_REQUEST = 'PAGE_FETCH_REQUEST';
export const PAGE_FETCH_SUCCESS = 'PAGE_FETCH_SUCCESS';
export const PAGE_FETCH_ERROR = 'PAGE_FETCH_ERROR';
