FROM node:10.13.0-alpine

RUN mkdir /app
WORKDIR /app
RUN cd /app

COPY ./package.json /app
COPY ./dist/server/index.js /app
COPY ./dist/server/views/index.ejs /app/views/

EXPOSE 3000

RUN yarn --production
CMD ["node", "./"]
