name: Release
on: workflow_dispatch

jobs:
  release:
    name: Release

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [22.14.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
        name: Run codegen
        run: npm run codegen

      - name: Lint code
        run: npm run lint

      - env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
        name: Build application
        run: npm run build

      - env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        run: npm run release
