# eslint-disable yml/sort-keys

name: Production
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - run: npm run codegen
        env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
      - run: npm run lint
      - run: npm run build
        env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ./.infrastructure
      - name: Terraform init
        id: init
        run: |
          terraform init \
          -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
          -backend-config="key=${{ secrets.TF_BACKEND_KEY }}" \
          -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" \
          -backend-config="access_key=${{ secrets.TF_BACKEND_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.TF_BACKEND_SECRET_KEY }}"
        working-directory: ./.infrastructure
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./.infrastructure
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color \
          --var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          --var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --var "cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}" \
          --var "cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
        working-directory: ./.infrastructure
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Terraform apply
        run: |
          terraform apply -auto-approve \
          --var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          --var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --var "cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}" \
          --var "cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
        working-directory: ./.infrastructure
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: sync s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: out
      - name: invalidate cloudfront cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: /*
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
